name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Flutter pub get
        run: flutter pub get

      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: Disable Code Signing
        run: |
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = "";/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Check Signing Configuration
        run: |
          grep -R "DEVELOPMENT_TEAM" ios/Runner.xcodeproj/project.pbxproj || true
          grep -R "CODE_SIGN_STYLE" ios/Runner.xcodeproj/project.pbxproj || true

      - name: Build iOS
        run: |
          flutter build ios \
            --release \
            --no-codesign
        env:
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGNING_REQUIRED: NO

      - name: Create Payload Folder
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move App Into Payload
        run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Create IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Flutter-iOS-IPA
          path: build/ios/iphoneos/FlutterIpaExport.ipa
