name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Flutter pub get
        run: flutter pub get

      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: Build iOS
        run: flutter build ios --release --no-codesign
        env:
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGNING_REQUIRED: NO

      - name: Create Payload
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app
        run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Create IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Flutter-iOS-IPA
          path: build/ios/iphoneos/FlutterIpaExport.ipa
